chain.DirectPrePay: parameterCheckHandler,prepayOrderHandler
chain.DirectPay: parameterCheckHandler,directPayHandler,mercOrderHandler,unifiedOrderHandler
chain.DepositRecharge: parameterCheckHandler,mercOrderHandler,unifiedOrderHandler,depositRechargeHandler
chain.WithdrApply: parameterCheckHandler,withdrApplyHandler
chain.WithdrAudit: parameterCheckHandler,withdrAuditHandler
chain.OrderRefund: parameterCheckHandler,mercOrderRefundHandler
chain.QueryOrderRefund: parameterCheckHandler,queryOrderRefundHandler
chain.PayCashier: parameterCheckHandler,payCashierHandler
chain.QueryOrder: parameterCheckHandler,queryOrderHandler
chain.QueryWithdrOrder: parameterCheckHandler,queryWithdrOrderHandler
chain.QueryBank: parameterCheckHandler,queryBankHandler
chain.QueryCardBind: parameterCheckHandler,queryCardBindHandler
chain.QueryBalance: queryBalanceHandler
chain.QueryBalanceBatch: queryBalanceBatchHandler
chain.QueryWithdrBank: queryWithdrBankHandler
chain.CardBind: cardBindHandler
chain.CardBindSms: cardBindSmsHandler
chain.CardBindConfirm: cardBindConfirmHandler
chain.UnCardBind: unCardBindHandler
chain.UserRealName: userRealNameHandler
chain.UserRealNameDetailsList: userRealNameDetailsListHandler
chain.QuickBankQuery: quickBankQueryHandler
chain.QuickSign: parameterCheckHandler,quickSignHandler
chain.QuickSignSms: parameterCheckHandler,quickSignSmsHandler
chain.QuickSignConfirm: parameterCheckHandler,quickSignConfirmHandler
chain.QuickPayReq: parameterCheckHandler,quickPayReqHandler,quickMercOrderHandler,quickUnifiedOrderHandler
chain.QuickPaySms: parameterCheckHandler,quickPaySmsHandler
chain.QuickPayConfirm: parameterCheckHandler,quickPayConfirmHandler
chain.QueryWthdrCardBind: parameterCheckHandler,queryWthdrCardBindHandler
chain.QueryQuickCardBind: parameterCheckHandler,queryQuickCardBindHandler
chain.WithdrApplyErrorCheck: parameterCheckHandler,withdrApplyErrorCheckHandler
chain.GetAppId: getAppIdHandler
chain.UserAddOrUpdate: userAddOrUpdateHandler
chain.CommonValue: commonValueHandler

