regs.methodType: "\\w{4,32}"
regs.busiType: "01|02|03|04|05|06|07|08|09"
regs.tradeCode: "01|02|03|04|05|06|07|08|09"
regs.mercId: "[0-9]{4,15}"
regs.platform: "MPMALL|MPWJMALL|MWJMALL|MNLMALL|XFYLMALL|ZBMALL|ZBGMALL|ZBGWJMALL"
regs.requestId: "\\d+"
regs.mobile: ".+"
regs.goodsId: ".+"
regs.goodsName: ".+"
regs.price: "^(([1-9]{1}\\d*)|([0]{1}))(\\.(\\d){0,2})?$"
regs.tradeType: "JSAPI|APP|NATIVE|MICROPAY|MWEB|PUBLIC|WX-PUBLIC"
regs.userIp: "(\\d+)\\.(\\d+)\\.(\\d+)\\.(\\d+)"
regs.sign: ".+"
regs.nickname: ".+"
regs.prePayNo: "\\w{4,32}"
regs.outTradeNo: "\\w{4,32}"
regs.orderNo: "\\w{4,32}"
regs.orderDate: "^2[0-9]{3}-[0-9]{2}-[0-9]{2}"
regs.orderTime: "[0-9]{2}:[0-9]{2}:[0-9]{2}"
regs.reqDate: "^2[0-9]{3}-[0-9]{2}-[0-9]{2}"
regs.reqTime: "[0-9]{2}:[0-9]{2}:[0-9]{2}"
regs.state: "\\d"
regs.type: "\\w+"
regs.bankCode: ".+"
regs.callbackUrl: "^(http|https)://[\\w.]*(\\:)*\\w*(\\/\\w*)*(\\w*.\\w*)*"
regs.notifyUrl: "^(http|https)://[\\w.]*(\\:)*\\w*(\\/\\w*)*(\\w*.\\w*)*"
regs.sysCnl: "IOS|ANDROID|WEB|WX-APPLET|WX-PUBLIC|H5|APP"
regs.appId: "\\w{4,64}"
regs.openId: ".+"
regs.startDate: "^2[0-9]{3}-[0-9]{2}-[0-9]{2}"
regs.endDate: "^2[0-9]{3}-[0-9]{2}-[0-9]{2}"
regs.findPage: "\\d"
regs.pageSize: "\\d"
regs.X-MP-SignVer: "\\w+"
regs.X-MPMALL-SignVer: "\\w+"
regs.refundNo: "\\w{4,32}"
regs.expand: "((\\w+\\:\\w+)\\;*)*"
regs.alias: ".+"
regs.effDate: "^2[0-9]{3}-[0-9]{2}-[0-9]{2}"
regs.expDate: "^2[0-9]{3}-[0-9]{2}-[0-9]{2}"
regs.remark: ".{1,100}"
regs.userId: "\\w+"
regs.userIds: ".+"
regs.name: ".+"
regs.orderStatus: "A|C|W|R"
regs.period: "[0-9]{1,2}"
regs.periodUnit: "[0-9]{2}"
regs.clientIp: ".+"
regs.telephone: "^0\\d{2,3}-\\d{7,8}(-\\d{1,4}){0,1}"
regs.tel: "\\w{6,13}"
regs.email: "(\\w+\\.*?\\w+){2,128}@(\\w+\\.+?\\w+){1,67}"
regs.bankType: "[0-9]{1}"
regs.bankCardName: ".+"
regs.bankCardNo: ".+"
regs.bankCardType: "01|02|05|08"
regs.bankNo: "\\w+"
regs.bankProv: "\\w+"
regs.bankCity: "\\w+"
regs.checkName: "NO_CHECK|FORCE_CHECK"
regs.cardNo: ".+"
regs.cardType: "[0-9]{1,2}"
regs.validDate: ".+"
regs.cvn2: ".+"
regs.agrNo: ".+"
regs.imgFront: ".+"
regs.imgBack: ".+"
regs.page: "\\d+"
regs.limit: "\\d+"
regs.realSource: "\\d+"
regs.timestamp: "\\d+"
regs.smsOrderNo: ".+"
regs.smsOrderType: "0|1|2|3"
regs.smsCode: "\\d+"
regs.payType: "1|2|3"
regs.bankCardImgFront: ".+"
regs.realType: "0|1"
regs.userToken:  ".+"
regs.agencyId:  ".+"
regs.routecode:  ".+"
regs.operType:  "1|2|3"
regs.refundOrderNo:  ".+"
regs.withdrPrice: "^(([1-9]{1}\\d*)|([0]{1}))(\\.(\\d){0,2})?$"
regs.withdrRatio: "^(([1-9]{1}\\d*)|([0]{1}))(\\.(\\d){0,3})?$"